# ~/.config/starship.toml
add_newline = false
format = """$directory$character"""
right_format = """$all"""
scan_timeout = 0
command_timeout = 1000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜](bold green)'

[git_branch]
symbol = "\uf418 "
format = '[ $symbol$branch(:$remote_branch) ]($style) '
style = 'bg:white fg:bold black'
disabled=false

[git_status]
disabled = true

[aws]
format = '[ $symbol($profile )(\($region\)) ]($style)'
disabled = false
style = 'bg:yellow fg:bold black'
symbol = " "

[cmd_duration]
disabled = true
